---
- name: gather facts
  hosts: local
  connection: local
  # ansible collects the info of the target server,before it executes any other facts
  tasks:
    - name: facts
      ansible.builtin.debug:
        msg: " {{ ansible_facts }}"
